# Generated by Django 2.1.2 on 2019-02-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcustomer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
